### ISSUE TITLE
TypeError: Cannot read property 'join' of undefined

### ISSUE THREAD

**Issue by turt2live** [turt2live/matrix-voyager-bot#136]

**Comment by turt2live** [comment]
No longer visible in logs.

**Comment by turt2live** [comment]
This happened.

```
Jun-30-2017 06:11:23.043 +00:00 error [VoyagerBot] Error updating node !RoiXcxpapaOlecWHem:dereferenced.org
Jun-30-2017 06:11:23.043 +00:00 error [VoyagerBot] Cannot read property 'join' of undefined
TypeError: Cannot read property 'join' of undefined
    at _client.getRoomState.then.state (/root/matrix-voyager-bot/src/VoyagerBot.js:282:152)
    at tryCatcher (/root/matrix-voyager-bot/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/root/matrix-voyager-bot/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/root/matrix-voyager-bot/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/root/matrix-voyager-bot/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/root/matrix-voyager-bot/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/root/matrix-voyager-bot/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/root/matrix-voyager-bot/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/root/matrix-voyager-bot/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
```
