### ISSUE TITLE
Graph crashes when clicking on a icon in chrome windows

### ISSUE THREAD

**Issue by MTRNord** [turt2live/matrix-voyager-bot#142]
I clicked on a icon and it greyed out and console was full of this error:

```
ERROR TypeError: Cannot read property 'id' of null
    at GraphComponent.isConnected (https://voyager.t2bot.io/js/app.8abde03d465cdd07d794.js:141:18870)
    at https://voyager.t2bot.io/js/app.8abde03d465cdd07d794.js:141:16819
    at Array.forEach (native)
    at GraphComponent.render (https://voyager.t2bot.io/js/app.8abde03d465cdd07d794.js:141:16770)
    at GraphComponent.onTick (https://voyager.t2bot.io/js/app.8abde03d465cdd07d794.js:141:15960)
    at Object.<anonymous> (https://voyager.t2bot.io/js/app.8abde03d465cdd07d794.js:141:14410)
    at Dispatch.call (https://voyager.t2bot.io/js/vendor.8abde03d465cdd07d794.js:676:104911)
    at step (https://voyager.t2bot.io/js/vendor.8abde03d465cdd07d794.js:543:11342)
    at timerFlush (https://voyager.t2bot.io/js/vendor.8abde03d465cdd07d794.js:494:26430)
    at wake (https://voyager.t2bot.io/js/vendor.8abde03d465cdd07d794.js:494:26499)
    at ZoneDelegate.invokeTask (https://voyager.t2bot.io/js/polyfills.8abde03d465cdd07d794.js:50:8356)
    at Object.onInvokeTask (https://voyager.t2bot.io/js/vendor.8abde03d465cdd07d794.js:176:9454)
    at ZoneDelegate.invokeTask (https://voyager.t2bot.io/js/polyfills.8abde03d465cdd07d794.js:50:8277)
    at Zone.runTask (https://voyager.t2bot.io/js/polyfills.8abde03d465cdd07d794.js:50:3409)
    at ZoneTask.invoke (https://voyager.t2bot.io/js/polyfills.8abde03d465cdd07d794.js:50:9385)
    at timer (https://voyager.t2bot.io/js/polyfills.8abde03d465cdd07d794.js:29:85)
```

**Comment by MTRNord** [comment]
![image](https://user-images.githubusercontent.com/1374914/27722666-41f51734-5d69-11e7-84e3-e180c06472dc.png)

**Comment by turt2live** [comment]
I can't reproduce this - is there a particular node that causes the issue or is it any of them?

**Comment by MTRNord** [comment]
well I more or less clicked something by accident. So not sure if it is a particular node. I zoomed with touch and that happened. It was still loading

**Comment by MTRNord** [comment]
Can't reproduce it a second time :/ Not sure what I did

**Comment by turt2live** [comment]
It might have been an intermittent issue while the graph updated (the bundle switched quite close to this ticket being created).

If it happens again, please do open a ticket :)

**Comment by MTRNord** [comment]
Well if I do it while still loading it comes up pretty random. Maybe it is becaause the node isn't rendered yet?

**Comment by MTRNord** [comment]
I think it could be the combination of zooing out clicking and by hat pressing multiple nodes

**Comment by turt2live** [comment]
The dragging stuff should be moved in https://github.com/turt2live/matrix-voyager-bot/issues/132 - but I'll keep this open as a reminder to test the case when physics is enabled.

**Comment by MTRNord** [comment]
Yep in tests I can better reproduce it using:
1. wait until  it starts rendering
2. while still rendering zoom out
3. click at many nodes at once if you see enough of them.
I guess as you just said it seems to be a touch/dragging issue
